#! /bin/bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" swag
usermod -o -u "$PUID" swag

echo '
-------------------------------------
 ___  __    __    __  __     ____
/ __| \ \  /  \  / / /  \   / __/_
\__ \  \ \/ /\ \/ / / __ \ | |_/  \
|___/   \__/  \__/ /_/  \_\ \___/|_|

-------------------------------------'
-------------------------------------
echo "
User uid:    $(id -u swag)
User gid:    $(id -g swag)
-------------------------------------
"

time32="$(date +%Y)"

if [[ "${time32}" == "1970" || "${time32}" == "1969" ]] && [ "$(uname -m)" == "armv7l" ]; then
  echo '
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Your DockerHost is most likely running an outdated version of libseccomp

To fix this, please visit https://docs.linuxserver.io/faq#libseccomp

Some apps might not behave correctly without this

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
'
fi

chown swag:swag /app
chown swag:swag /config
chown swag:swag /defaults