#!/usr/bin/with-contenv bash

# Check for custom user group id
PUID=${PUID:-911}
PGID=${PGID:-911}

# Update user and group id of secproxy user
groupmod -o -g "$PGID" secproxy >/dev/null
usermod -o -u "$PUID" secproxy >/dev/null

echo '-------------------------------------'
echo "User uid:    $(id -u secproxy)
User gid:    $(id -g secproxy)
-------------------------------------"

# Set permission for secproxy user
chown secproxy:secproxy /config
chown secproxy:secproxy /default


# make sure all environment variables are lower case and properly formated
UPDATE_CONFIGURATION=$(echo "${UPDATE_CONFIGURATION,,}")
UPDATE_CONFIGURATION=$(echo "${UPDATE_CONFIGURATION}" | sed "s/\"//g")


# Copy template files if not exist
for i in $(find /default -type f)
do
    CONFIG_PATH="$(echo $i | sed -e "s/^\/default/\/config/")"
    CONFIG_DIR="$(echo "$(dirname "${CONFIG_PATH}")")"

	# Create directory if not exists
	mkdir -p $CONFIG_DIR

	# Check if automatic update was configured
	if [[ ${UPDATE_CONFIGURATION} = "enabled" ]]; then
		# If automatic update do not overwrite bots.d and sites-available as this impacts the user configuration
		if [[ ${CONFIG_PATH} != "/config/nginx/sites-available/"* ]] && [[ ${CONFIG_PATH} != "/config/nginx/bots.d/"* ]]; then
			cp $i $CONFIG_PATH
		fi
	elif [[ ! -f $CONFIG_PATH ]]; then
		# Copy only new files if automatic update was disabled
		cp $i $CONFIG_PATH
	fi
done
sleep 1