#!/usr/bin/with-contenv bash

# Create log folder
mkdir -p /config/logs/nginx

# Create modsecurity log
touch /config/logs/nginx/modsec_audit.log

# Link log folder to default location
rm -rf /var/log/nginx
ln -s /config/logs/nginx /var/log/nginx

# Download dhparam key from https://2ton.com.au/dhtool/
if [[ ! -f "/config/nginx/dhparam4096.pem" ]] || ! grep -q 'PARAMETERS' "/config/nginx/dhparam4096.pem"; then
    echo "**** downloading fresh generated 4096 dhparam key ****"
    echo "**** this process can not guarantee a unique key ****"
    echo "**** for more security create a your own dhparam ****"
    curl -s https://2ton.com.au/dhparam/4096 > /config/nginx/dhparam4096.pem
	sleep 1
fi
if ! grep -q 'PARAMETERS' "/config/nginx/dhparam4096.pem"; then
  # Check again for dhparam to avoid long running generation
  sleep 1
  if ! grep -q 'PARAMETERS' "/config/nginx/dhparam4096.pem"; then
    echo "Generating dhparams.pem. This will take a long time. Do not stop the container until this process is completed."
    openssl dhparam -out /config/nginx/dhparam4096.pem 4096
  fi
fi

# Generate nginx log files
if [[ ! -f /config/logs/nginx/error.log ]]; then
	touch /config/logs/nginx/error.log
fi
if [[ ! -f /config/logs/nginx/access.log ]]; then
	touch /config/logs/nginx/access.log
fi

# Download/update bad bot, blocking and serval other lists
chmod +x /etc/scripts.d/refresh-agent.sh
chmod +x /etc/scripts.d/refresh-agent-weekly.sh
/etc/scripts.d/refresh-agent.sh
/etc/scripts.d/refresh-agent-weekly.sh
sleep 1
