#!/usr/bin/with-contenv bash

# Create additional folders
mkdir -p /config/logs/fail2ban
mkdir -p /var/run/fail2ban

# make sure all environment variables are lower case and properly formated
FAIL2BAN_MAIL_REPORT=$(echo "${FAIL2BAN_MAIL_REPORT,,}")
FAIL2BAN_MAIL_REPORT=$(echo "${FAIL2BAN_MAIL_REPORT}" | sed "s/\"//g")

# Update default action filter files as they should not contain user specific configuration
cp /default/fail2ban/action.d/*.conf /config/fail2ban/action.d/
cp /default/fail2ban/filter.d/*.conf /config/fail2ban/filter.d/


# Replace fail2ban config in /etc directory with user config
if [[ -d /etc/fail2ban/filter.d ]]; then
	rm -rf /etc/fail2ban/filter.d
fi
if [[ -d /etc/fail2ban/action.d ]]; then
	rm -rf /etc/fail2ban/action.d
fi
cp -R /config/fail2ban/filter.d /etc/fail2ban/
cp -R /config/fail2ban/action.d /etc/fail2ban/
cp /config/fail2ban/fail2ban.local /etc/fail2ban/fail2ban.local
cp /config/fail2ban/jail.local /etc/fail2ban/jail.local
cp /config/fail2ban/paths-common.local /etc/fail2ban/paths-common.local

# Generate fail2ban log files
if [[ ! -f /config/logs/fail2ban/fail2ban.log ]]; then
	touch /config/logs/fail2ban/fail2ban.log
fi

# Configure mail settings if available
if [[ ${FAIL2BAN_MAIL_REPORT} != "disabled" ]] && [[ -n $SMTP_SERVER ]] && [[ -n $SMTP_SENDER_MAIL ]] && [[ -n $SMTP_SENDER_NAME ]] && [[ -n $SMTP_RECEIVER ]]; then
  echo "**** Enabling fail2ban mail notifications ****"
  
  ORIGINAL_MAIL_ACTION="#action = %(action_mw)s\[from=<sendermail>, password=<secretpassword>, destination=<destinationmail>, sendername=<sendername>, smtpserver=<smtpserver>\]"
  MAIL_ACTION="action = %(action_mw)s\[from=${SMTP_SENDER_MAIL}, password=<smtppassword>, destination=${SMTP_RECEIVER}, sendername=${SMTP_SENDER_NAME}, smtpserver=${SMTP_SERVER}\]"

  # Check if smtp was configured with password file
  if [[ -n $SMTP_PASSWORD_FILE ]]; then
	if [ -s "$SMTP_PASSWORD_FILE" ]; then
		SMTP_PASSWORD="$(head -n 1 $SMTP_PASSWORD_FILE)"		
	else
		echo "ERROR: SMTP password file does not exist or is empty. Can not enable fail2ban mail notifications. Please check your smtp server variables"
	fi;
  fi

  # Check if smtp password is available	
  if [[ -n $SMTP_PASSWORD ]]; then
	
	# Duplicate (%) as sendmail will interpret this as command if there is a single (%)
	SMTP_PASSWORD=$(sed -e "s/%/%%/g" <<< $SMTP_PASSWORD)
	
	# Add password to mail action
	MAIL_ACTION=$(sed -e "s/<smtppassword>/$SMTP_PASSWORD/g" <<< $MAIL_ACTION)

	# Write smtp config to config file
	sed -i "s/${ORIGINAL_MAIL_ACTION}/${MAIL_ACTION}/" /etc/fail2ban/jail.local
	sed -i "s/#sender = root@localhost/sender = ${SMTP_SENDER_MAIL}/" /etc/fail2ban/jail.local
	sed -i "s/#destemail = root@localhost/destemail = ${SMTP_RECEIVER}/" /etc/fail2ban/jail.local
  else
	echo "ERROR: SMTP Server details choosen but no password available. Can not enable fail2ban mail notifications. Please check your smtp server variables."
  fi
fi

# Clear SMTP_PASSWORD from variables
SMTP_PASSWORD=""
MAIL_ACTION=""